//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int chat_id { get; set; }
        public string nombre_usuario_no_reg { get; set; }
        public string emial_usuario_no_reg { get; set; }
        public System.DateTime fecha { get; set; }
        public string consulta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
