//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Excursiones
    {
        public int excursion_id { get; set; }
        public int atractivo_turistico_id { get; set; }
        public string detalle { get; set; }
    
        public virtual Atractivo_Turisticos Atractivo_Turisticos { get; set; }
        public virtual Excursiones Excursiones { get; set; }
    }
}
