//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foro_Debate
    {
        public int foro_id { get; set; }
        public int usuario_id { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Foro Foro { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
