//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tursArgBDEntities : DbContext
    {
        public tursArgBDEntities()
            : base("name=tursArgBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atractivo_Turisticos> Atractivo_Turisticos { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Excursiones> Excursiones { get; set; }
        public virtual DbSet<Foro> Foro { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Excursiones> Tipo_Excursiones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Detalle_Excursiones> Detalle_Excursiones { get; set; }
        public virtual DbSet<Foro_Debate> Foro_Debate { get; set; }
    }
}
